name: "sustitucion de variables"

on:
  workflow_dispatch:
  
jobs:
  iniciar: 
    uses: Demo-Pemex/template-netframework/.github/workflows/reemplazo.yml@main
    secrets:
      variables_json: '{"Clave1": "${{ secrets.SECRETO1 }}","Clave2": "${{ vars.VARIABLE1 }}"}'
    with:      
      ambiente: "dev"
