name: "JSON sustitucion de variables"

on:
  workflow_dispatch:
  
jobs:
  dev: 
    uses: Demo-Pemex/template-netframework/.github/workflows/reemplazo_json.yml@main    
    with:      
      ambiente: "dev"
    secrets:  
      secretos_json: '{"Clave1": "${{ secrets.SECRETO1 }}","Clave2": "${{ secrets.SECRETO2 }}","VARIABLE1": "${{ vars.VARIABLE1 }}"}'
  

  qa: 
    uses: Demo-Pemex/template-netframework/.github/workflows/reemplazo_json.yml@main    
    with:      
      ambiente: "qa"
    secrets:  
      secretos_json: '{"Clave1": "${{ secrets.SECRETO1 }}","Clave2": "${{ secrets.SECRETO2 }}"}'
