name: docker pipeline

on:
  push:
    branches:
      - master
      - main
env:
  #reponame tolower

  reponame: demo-pemex/demo-cicd-net
  registry: ghcr.io
jobs:
  push-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push to registry
        uses: docker/build-push-action@v2
        with:
          context: src/
          push: true
          #pass reponame tolower case
          tags: ${{ env.registry }}/${{ env.reponame }}:latest
          build-args: |
            --build-arg BUILDKIT_INLINE_CACHE=1
            --build-arg BUILDKIT_INLINE_CACHE_REMAP=1